name: AI-ARana

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the AI-ARana/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/AI-ARana -v ${{ github.workspace }}/_site:/srv/AI-ARana/_site \
        AI-ARana/builder: latest /bin/bash -c "chmod -R 777 /srv/AI-ARana && AI-ARana build --future"
